CREATE SCHEMA `indianmonuments` ;

CREATE TABLE USER(
    USERID   INT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWD VARCHAR(20) NOT NULL,
    FIRSTNAME VARCHAR(20) NOT NULL,
    LASTNAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    PRIMARY KEY(USERID)
);

CREATE TABLE MONUMENT(
    MONUMENTID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(200) NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
    ADD_LINE1 VARCHAR(100) NOT NULL,
    ADD_LINE2 VARCHAR(100),
    CITY VARCHAR(50) NOT NULL,
    IMAGEPATH VARCHAR(100) NOT NULL,
    OPENTIME0 VARCHAR(4),
    OPENTIME1 VARCHAR(4),
    OPENTIME2 VARCHAR(4),
    OPENTIME3 VARCHAR(4),
    OPENTIME4 VARCHAR(4),
    OPENTIME5 VARCHAR(4),
    OPENTIME6 VARCHAR(4),
    CLOSETIME0 VARCHAR(4),
    CLOSETIME1 VARCHAR(4),
    CLOSETIME2 VARCHAR(4),
    CLOSETIME3 VARCHAR(4),
    CLOSETIME4 VARCHAR(4),
    CLOSETIME5 VARCHAR(4),
    CLOSETIME6 VARCHAR(4),
    PRIMARY KEY(MONUMENTID)
);


CREATE TABLE MONUMENTPRICE(
    PRICEID INT NOT NULL AUTO_INCREMENT,
    MONUMENTID INT NOT NULL,

    DAYID INT NOT NULL,
    ADULTPRICE INT NOT NULL,
    CHILDPRICE INT NOT NULL,
    PRIMARY KEY(PRICEID),
    FOREIGN KEY (MONUMENTID) REFERENCES MONUMENT(MONUMENTID)

);

CREATE TABLE CART(
    CARTID INT NOT NULL AUTO_INCREMENT,
    USERID INT NOT NULL,
    TOTAL_PRICE INT NOT NULL,
    PRIMARY KEY(CARTID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID)
);

CREATE TABLE CARTITEM(
    ITEMID INT NOT NULL AUTO_INCREMENT,
    CARTID INT NOT NULL,
    MONUMENTID INT NOT NULL,
    CART_DATE DATE NOT NULL,
    CHILD_NUM INT,
    ADULT_NUM INT,
    DAYID INT NOT NULL,
    CHILD_PRICE INT NOT NULL,
    ADULT_PRICE INT NOT NULL,
    PRIMARY KEY(ITEMID),
    FOREIGN KEY (CARTID) REFERENCES CART(CARTID),
    FOREIGN KEY (MONUMENTID) REFERENCES MONUMENT(MONUMENTID)

);

CREATE TABLE MONUMENT_ORDER(
    ORDERID INT NOT NULL AUTO_INCREMENT,
    USERID INT NOT NULL,
    ORDER_STATUS VARCHAR(10) NOT NULL,
    TOTAL_PRICE INT NOT NULL,
    ORDER_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY(ORDERID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID)
);

CREATE TABLE ORDERITEM(
    ITEMID INT NOT NULL AUTO_INCREMENT,
    ORDERID INT NOT NULL,
    MONUMENTID INT NOT NULL,
    VISIT_DATE DATE NOT NULL,
    CHILD_NUM INT,
    ADULT_NUM INT,
    DAYID INT NOT NULL,
    CHILD_PRICE INT NOT NULL,
    ADULT_PRICE INT NOT NULL,
    PRIMARY KEY(ITEMID),
    FOREIGN KEY (ORDERID) REFERENCES MONUMENT_ORDER(ORDERID),
    FOREIGN KEY (MONUMENTID) REFERENCES MONUMENT(MONUMENTID)
);


INSERT INTO USER(USERNAME,PASSWD,FIRSTNAME,LASTNAME,EMAIL,ROLE) VALUES("admin", "admin", "Administrator", "", "admin@monuments.com", "ADMIN");

INSERT INTO USER(USERNAME,PASSWD,FIRSTNAME,LASTNAME,EMAIL,ROLE) VALUES("user", "password", "User", "Test", "user@monuments.com", "USER");